# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # This is the minimum Jenkins version
      - dependency-name: "org.jenkins-ci.main:cli"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
